# -*- coding: utf-8 -*-
"""Bank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12dPuKq5WIdDCAUQS-uo6gM6FZ3UjpfWG
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

bank = pd.read_csv('bank.csv')
bank.head(5)

age_co = np.corrcoef(bank.age, bank.y)
age_co

duration_co = np.corrcoef(bank.duration, bank.y)
duration_co